name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history to allow GitVersion to work

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install GitVersion
      run: dotnet tool install -g GitVersion.Tool

    - name: Use GitVersion to calculate version
      id: gitversion
      run: |
        GIT_VERSION=$(dotnet-gitversion /output json /showvariable FullSemVer)
        echo "GIT_VERSION=$GIT_VERSION" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release

    - name: Create and push tag
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        GIT_TAG: v${{ env.GIT_VERSION }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag $GIT_TAG
        git push origin $GIT_TAG

    - name: Publish NuGet Package
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: '6.0.x'

    - name: Push NuGet Package
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        for package in $(find . -name "*.nupkg"); do
          dotnet nuget push "$package" -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
        done
 